version: '3.5'
services:
  web-corecontrol-prod:
    build: .
    ports:
      - '80:80'
    restart: always
    environment:
      - 'REACT_APP_API_URL=http://3.126.123.50:8000/api/v1'
  web-corecontrol-qa:
    build: .
    ports:
      - '801:80'
    restart: always
    environment:
      - 'REACT_APP_API_URL=http://3.126.123.50:8001/api/v1'
  web-corecontrol-dev:
    build: .
    ports:
      - '802:80'
    restart: always
    environment:
      - 'REACT_APP_API_URL=http://3.126.123.50:8002/api/v1'
