version: '3.5'
services:

  web-corecontrol-prod:
    build: .
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env.production
  web-corecontrol-qa:
    build: .
    ports:
      - "801:80"
    restart: always
    env_file:
      - .env.qa
  web-corecontrol-dev:
    build: .
    ports:
      - "802:80"
    restart: always
    env_file:
      - .env.development